name: Zapor
version: ${project.version}
main: ru.danka.zapor.ZaporPlugin
commands:
  запор:
    description: Запор, хуле непонятно там все написано
    aliases:
      - запористо
      - пошлопозапору
      - срать
  габрираЗапор:
    description: как запор только с габрирой
    aliases:
      - габрира
      - балтика
  лехаблять:
    description: леха блять как в гм зайти я заспавнил скелета с мечом и он меня отпиздил

  раздачанаспаве:
    description: неважно

  писюн:
    description: навалить писюн

  погладить:
    description: погладить додика

  якубовна:

  запористыйинвентарь:

  загадка:
